import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Stream-0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
        <Layout />
      
    </div>
  )
}
